/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthLayoutRouteImport } from './routes/_auth/layout'
import { Route as AppLayoutRouteImport } from './routes/_app/layout'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppProtectedLayoutRouteImport } from './routes/_app/_protected/layout'
import { Route as AuthPasswordIndexRouteImport } from './routes/_auth/password.index'
import { Route as AuthPasswordResetRouteImport } from './routes/_auth/password.reset'
import { Route as AuthAuthErrorRouteImport } from './routes/_auth/auth.error'
import { Route as AppProtectedPageIdRouteImport } from './routes/_app/_protected/$pageId'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppProtectedLayoutRoute = AppProtectedLayoutRouteImport.update({
  id: '/_protected',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthPasswordIndexRoute = AuthPasswordIndexRouteImport.update({
  id: '/password/',
  path: '/password/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthPasswordResetRoute = AuthPasswordResetRouteImport.update({
  id: '/password/reset',
  path: '/password/reset',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthAuthErrorRoute = AuthAuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppProtectedPageIdRoute = AppProtectedPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => AppProtectedLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/': typeof AppIndexRoute
  '/$pageId': typeof AppProtectedPageIdRoute
  '/auth/error': typeof AuthAuthErrorRoute
  '/password/reset': typeof AuthPasswordResetRoute
  '/password': typeof AuthPasswordIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/': typeof AppIndexRoute
  '/$pageId': typeof AppProtectedPageIdRoute
  '/auth/error': typeof AuthAuthErrorRoute
  '/password/reset': typeof AuthPasswordResetRoute
  '/password': typeof AuthPasswordIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_app/_protected': typeof AppProtectedLayoutRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_protected/$pageId': typeof AppProtectedPageIdRoute
  '/_auth/auth/error': typeof AuthAuthErrorRoute
  '/_auth/password/reset': typeof AuthPasswordResetRoute
  '/_auth/password/': typeof AuthPasswordIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/'
    | '/$pageId'
    | '/auth/error'
    | '/password/reset'
    | '/password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/$pageId'
    | '/auth/error'
    | '/password/reset'
    | '/password'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/_protected'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/'
    | '/_app/_protected/$pageId'
    | '/_auth/auth/error'
    | '/_auth/password/reset'
    | '/_auth/password/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/_protected': {
      id: '/_app/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppProtectedLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_auth/password/': {
      id: '/_auth/password/'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof AuthPasswordIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/password/reset': {
      id: '/_auth/password/reset'
      path: '/password/reset'
      fullPath: '/password/reset'
      preLoaderRoute: typeof AuthPasswordResetRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/auth/error': {
      id: '/_auth/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthAuthErrorRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/_protected/$pageId': {
      id: '/_app/_protected/$pageId'
      path: '/$pageId'
      fullPath: '/$pageId'
      preLoaderRoute: typeof AppProtectedPageIdRouteImport
      parentRoute: typeof AppProtectedLayoutRoute
    }
  }
}

interface AppProtectedLayoutRouteChildren {
  AppProtectedPageIdRoute: typeof AppProtectedPageIdRoute
}

const AppProtectedLayoutRouteChildren: AppProtectedLayoutRouteChildren = {
  AppProtectedPageIdRoute: AppProtectedPageIdRoute,
}

const AppProtectedLayoutRouteWithChildren =
  AppProtectedLayoutRoute._addFileChildren(AppProtectedLayoutRouteChildren)

interface AppLayoutRouteChildren {
  AppProtectedLayoutRoute: typeof AppProtectedLayoutRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppProtectedLayoutRoute: AppProtectedLayoutRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthAuthErrorRoute: typeof AuthAuthErrorRoute
  AuthPasswordResetRoute: typeof AuthPasswordResetRoute
  AuthPasswordIndexRoute: typeof AuthPasswordIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthAuthErrorRoute: AuthAuthErrorRoute,
  AuthPasswordResetRoute: AuthPasswordResetRoute,
  AuthPasswordIndexRoute: AuthPasswordIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
